-- VHDL Entity pre_made.dummy_alien_replace_me.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 15:05:58  5.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY dummy_alien_replace_me IS
   PORT( 
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      hit         : IN     std_logic;
      rst_n       : IN     std_logic;
      alien_color : OUT    std_logic_vector (23 DOWNTO 0);
      alien_x     : OUT    std_logic_vector (7 DOWNTO 0);
      alien_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END dummy_alien_replace_me ;

--
-- VHDL Architecture pre_made.dummy_alien_replace_me.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 15:07:42  5.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF dummy_alien_replace_me IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT c2_t7_basic_alien
   PORT (
      clock          : IN     std_logic ;
      enable         : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      alien_defeated : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord        : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t7_basic_alien USE ENTITY alien_game_lib.c2_t7_basic_alien;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : c2_t7_basic_alien
      PORT MAP (
         clock          => clk,
         enable         => enable,
         hit            => hit,
         rst_n          => rst_n,
         alien_color    => alien_color,
         alien_defeated => OPEN,
         x_coord        => alien_x,
         y_coord        => alien_y
      );

END struct;
