-- VHDL Entity pre_made.HELLO_LED.symbol
--
-- Created:
--          by - kayra
--          at - 10:38:18 07/30/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY HELLO_LED IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      sw0            : IN     std_logic;
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      your_signals   : OUT    std_logic
   );

-- Declarations

END HELLO_LED ;

--
-- VHDL Architecture pre_made.HELLO_LED.struct
--
-- Created:
--          by - kayra
--          at - 12:02:15 08/21/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY pre_made;

ARCHITECTURE struct OF HELLO_LED IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color   : std_logic_vector(23 DOWNTO 0);
   SIGNAL x_coord : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT z_black_box
   PORT (
      clk            : IN     std_logic;
      color_BGR      : IN     std_logic_vector (23 DOWNTO 0);
      rst_n          : IN     std_logic;
      x_coord        : IN     std_logic_vector (7 DOWNTO 0);
      y_coord        : IN     std_logic_vector (7 DOWNTO 0);
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      your_signals   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : z_black_box USE ENTITY pre_made.z_black_box;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : z_black_box
      PORT MAP (
         clk            => clk,
         color_BGR      => color,
         rst_n          => rst_n,
         x_coord        => x_coord,
         y_coord        => y_coord,
         if_you_name    => if_you_name,
         iotre_will     => iotre_will,
         like_this      => like_this,
         of_this_course => of_this_course,
         throw_you_out  => throw_you_out,
         your_signals   => your_signals
      );

END struct;
