-- VHDL Entity alien_game_lib.c1_t3c_hello_led.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 13:55:56 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3c_hello_led IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw0       : IN     std_logic;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c1_t3c_hello_led ;

--
-- VHDL Architecture alien_game_lib.c1_t3c_hello_led.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 13:55:56 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_t3c_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color  : std_logic_vector(23 DOWNTO 0);
   SIGNAL color1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL x      : std_logic_vector(7 DOWNTO 0);
   SIGNAL x1     : std_logic_vector(7 DOWNTO 0);
   SIGNAL y      : std_logic_vector(7 DOWNTO 0);
   SIGNAL y1     : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c1_t3_hello_led
   PORT (
      color : OUT    std_logic_vector (23 DOWNTO 0);
      x     : OUT    std_logic_vector (7 DOWNTO 0);
      y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c1_t3b_hello_led
   PORT (
      btn   : IN     std_logic_vector (3 DOWNTO 0);
      color : OUT    std_logic_vector (23 DOWNTO 0);
      x     : OUT    std_logic_vector (7 DOWNTO 0);
      y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t3_hello_led USE ENTITY alien_game_lib.c1_t3_hello_led;
   FOR ALL : c1_t3b_hello_led USE ENTITY alien_game_lib.c1_t3b_hello_led;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(x, x1, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => x_coord <= x;
      WHEN '1' => x_coord <= x1;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(y, y1, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => y_coord <= y;
      WHEN '1' => y_coord <= y1;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(color, color1, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => color_BGR <= color;
      WHEN '1' => color_BGR <= color1;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_3 : c1_t3_hello_led
      PORT MAP (
         color => color,
         x     => x,
         y     => y
      );
   U_4 : c1_t3b_hello_led
      PORT MAP (
         btn   => btn,
         color => color1,
         x     => x1,
         y     => y1
      );

END struct;
