-- VHDL Entity alien_game_lib.c1_t3b_hello_led.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 13:05:26 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3b_hello_led IS
   PORT( 
      btn   : IN     std_logic_vector (3 DOWNTO 0);
      color : OUT    std_logic_vector (23 DOWNTO 0);
      x     : OUT    std_logic_vector (7 DOWNTO 0);
      y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c1_t3b_hello_led ;

--
-- VHDL Architecture alien_game_lib.c1_t3b_hello_led.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 13:05:20 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t3b_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din5 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   din0 <= "000000000000000100101100";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   din1 <= "000000000000000001100110";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   din2 <= "00001100";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   din3 <= "00001111";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   din4 <= "00011001";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din5 <= "00000111";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(din0, din1, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => color <= din0;
      WHEN '1' => color <= din1;
      WHEN OTHERS => color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(din2, din3, btn)
   BEGIN
      CASE btn(1) IS
      WHEN '0' => x <= din2;
      WHEN '1' => x <= din3;
      WHEN OTHERS => x <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(din4, din5, btn)
   BEGIN
      CASE btn(2) IS
      WHEN '0' => y <= din4;
      WHEN '1' => y <= din5;
      WHEN OTHERS => y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
