-- VHDL Entity alien_game_lib.c1_t3_hello_led.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 10:44:52 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3_hello_led IS
   PORT( 
      color : OUT    std_logic;
      x     : OUT    std_logic;
      y     : OUT    std_logic
   );

-- Declarations

END c1_t3_hello_led ;

--
-- VHDL Architecture alien_game_lib.c1_t3_hello_led.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 10:44:52 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t3_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   x <= '1';

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   y <= '0';

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   color <= '1';

   -- Instance port mappings.

END struct;
