-- VHDL Entity alien_game_lib.c2_t7_basic_alien.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 16:10:10  5.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_basic_alien IS
   PORT( 
      clock          : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      alien_defeated : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord        : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord        : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t7_basic_alien ;

--
-- VHDL Architecture alien_game_lib.c2_t7_basic_alien.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 16:10:10  5.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t7_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT c2_t7_color
   PORT (
      clk         : IN     std_logic ;
      hit         : IN     std_logic ;
      rst_n       : IN     std_logic ;
      alien_color : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t7_coordinate
   PORT (
      clock   : IN     std_logic ;
      enable  : IN     std_logic ;
      rst_n   : IN     std_logic ;
      x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t7_color USE ENTITY alien_game_lib.c2_t7_color;
   FOR ALL : c2_t7_coordinate USE ENTITY alien_game_lib.c2_t7_coordinate;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : c2_t7_color
      PORT MAP (
         clk         => clock,
         hit         => hit,
         rst_n       => rst_n,
         alien_color => alien_color
      );
   U_0 : c2_t7_coordinate
      PORT MAP (
         clock   => clock,
         enable  => enable,
         rst_n   => rst_n,
         x_coord => x_coord,
         y_coord => y_coord
      );

END struct;
