-- VHDL Entity alien_game_lib.c2_t2_decrementer.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 13:58:37 30.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_decrementer IS
   PORT( 
      input_decrementer  : IN     std_logic_vector (2 DOWNTO 0);
      output_decrementer : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c2_t2_decrementer ;

--
-- VHDL Architecture alien_game_lib.c2_t2_decrementer.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 14:56:23 30.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t2_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry_in  : std_logic;
   SIGNAL carry_in1 : std_logic;
   SIGNAL input_1   : std_logic;
   SIGNAL input_2   : std_logic;
   SIGNAL sw1       : std_logic;


   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c2_t2_full_adder
   PORT (
      carry_in  : IN     std_logic ;
      input_0   : IN     std_logic ;
      input_1   : IN     std_logic ;
      carry_out : OUT    std_logic ;
      sum       : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   FOR ALL : c2_t2_full_adder USE ENTITY alien_game_lib.c2_t2_full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   sw1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   input_1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   input_2 <= '1';

   -- Instance port mappings.
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => input_decrementer(0),
         sw1   => sw1,
         carry => carry_in,
         sum   => output_decrementer(0)
      );
   U_2 : c2_t2_full_adder
      PORT MAP (
         carry_in  => carry_in,
         input_0   => input_1,
         input_1   => input_decrementer(1),
         carry_out => carry_in1,
         sum       => output_decrementer(1)
      );
   U_4 : c2_t2_full_adder
      PORT MAP (
         carry_in  => carry_in1,
         input_0   => input_2,
         input_1   => input_decrementer(2),
         carry_out => OPEN,
         sum       => output_decrementer(2)
      );

END struct;
