-- VHDL Entity alien_game_lib.c2_t2_full_adder.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 14:31:51 30.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_full_adder IS
   PORT( 
      carry_in  : IN     std_logic;
      input_0   : IN     std_logic;
      input_1   : IN     std_logic;
      carry_out : OUT    std_logic;
      sum       : OUT    std_logic
   );

-- Declarations

END c2_t2_full_adder ;

--
-- VHDL Architecture alien_game_lib.c2_t2_full_adder.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 14:31:46 30.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t2_full_adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic;
   SIGNAL din1 : std_logic;
   SIGNAL dout : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout <= carry_in AND din0;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   din1 <= input_1 AND input_0;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   carry_out <= dout OR din1;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'xor'
   din0 <= input_1 XOR input_0;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   sum <= din0 XOR carry_in;

   -- Instance port mappings.

END struct;
