-- VHDL Entity alien_game_lib.c2_t7_color.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-704-SPC)
--          at - 16:22:19  8.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_color IS
   PORT( 
      clk         : IN     std_logic;
      hit_count   : IN     std_logic_vector (1 DOWNTO 0);
      rst_n       : IN     std_logic;
      alien_color : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c2_t7_color ;

--
-- VHDL Architecture alien_game_lib.c2_t7_color.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-704-SPC)
--          at - 16:22:19  8.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t7_color IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d     : std_logic_vector(23 DOWNTO 0);
   SIGNAL din2  : std_logic_vector(23 DOWNTO 0);
   SIGNAL din3  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL alien_color_internal : std_logic_vector (23 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(23 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   alien_color_internal <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_5reg_cval <= "111111110000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= d;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'magenta' of 'constval'
   din2 <= "100010110000000010001011";

   -- ModuleWare code(v1.12) for instance 'purple' of 'constval'
   dout2 <= "111011101000001011101110";

   -- ModuleWare code(v1.12) for instance 'white' of 'constval'
   din3 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(alien_color_internal, dout2, din2, din3, 
                          hit_count)
   BEGIN
      CASE hit_count IS
      WHEN "00" => d <= alien_color_internal;
      WHEN "01" => d <= dout2;
      WHEN "10" => d <= din2;
      WHEN "11" => d <= din3;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   alien_color <= alien_color_internal;

END struct;
