-- VHDL Entity alien_game_lib.c3_t2_fpga_implementation.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-715-SPC)
--          at - 16:33:48 21.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t2_fpga_implementation IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      of_this_course : OUT    std_logic
   );

-- Declarations

END c3_t2_fpga_implementation ;

--
-- VHDL Architecture alien_game_lib.c3_t2_fpga_implementation.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-715-SPC)
--          at - 16:33:48 21.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY pre_made;

ARCHITECTURE struct OF c3_t2_fpga_implementation IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_color   : std_logic_vector(23 DOWNTO 0);
   SIGNAL d             : std_logic_vector(23 DOWNTO 0);
   SIGNAL d1            : std_logic_vector(7 DOWNTO 0);
   SIGNAL d2            : std_logic_vector(7 DOWNTO 0);
   SIGNAL enable        : std_logic;
   SIGNAL frame_done    : std_logic;
   SIGNAL gun_color     : std_logic_vector(23 DOWNTO 0);
   SIGNAL gun_px_idx    : std_logic_vector(2 DOWNTO 0);
   SIGNAL module_select : std_logic_vector(1 DOWNTO 0);
   SIGNAL q             : std_logic_vector(7 DOWNTO 0);
   SIGNAL q1            : std_logic_vector(7 DOWNTO 0);
   SIGNAL q2            : std_logic_vector(23 DOWNTO 0);
   SIGNAL w_rdy         : std_logic;
   SIGNAL write         : std_logic;
   SIGNAL x_coord       : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_coord1      : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord       : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord1      : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_8' of 'adff'
   SIGNAL mw_U_8reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic_vector(23 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t7_basic_alien
   PORT (
      clock          : IN     std_logic ;
      enable         : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      alien_defeated : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord        : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t1_gun_module
   PORT (
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic ;
      enable     : IN     std_logic ;
      gun_px_idx : IN     std_logic_vector (2 DOWNTO 0);
      rst_n      : IN     std_logic ;
      gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t2_write_sequencer
   PORT (
      clk           : IN     std_logic ;
      rst_n         : IN     std_logic ;
      write_ready   : IN     std_logic ;
      enable        : OUT    std_logic ;
      frame_done    : OUT    std_logic ;
      gun_px_idx    : OUT    std_logic_vector (2 DOWNTO 0);
      module_select : OUT    std_logic_vector (1 DOWNTO 0);
      write         : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT z_black_box_y
   PORT (
      clk            : IN     std_logic;
      color_BGR      : IN     std_logic_vector (23 DOWNTO 0);
      frame_done     : IN     std_logic;
      rst_n          : IN     std_logic;
      write          : IN     std_logic;
      x_coord        : IN     std_logic_vector (7 DOWNTO 0);
      y_coord        : IN     std_logic_vector (7 DOWNTO 0);
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      w_rdy          : OUT    std_logic;
      your_signals   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t7_basic_alien USE ENTITY alien_game_lib.c2_t7_basic_alien;
   FOR ALL : c3_t1_gun_module USE ENTITY alien_game_lib.c3_t1_gun_module;
   FOR ALL : c3_t2_write_sequencer USE ENTITY alien_game_lib.c3_t2_write_sequencer;
   FOR ALL : z_black_box_y USE ENTITY pre_made.z_black_box_y;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   q <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_7reg_cval <= "00000001";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= d2;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'adff'
   q1 <= mw_U_8reg_cval;
   u_8seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_8reg_cval <= "00000001";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_8reg_cval <= d1;
      END IF;
   END PROCESS u_8seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'adff'
   q2 <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_9reg_cval <= "000000000000000100000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_9reg_cval <= d;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(x_coord, x_coord1, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => d2 <= x_coord;
      WHEN "01" => d2 <= x_coord1;
      WHEN OTHERS => d2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(y_coord, y_coord1, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => d1 <= y_coord;
      WHEN "01" => d1 <= y_coord1;
      WHEN OTHERS => d1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(alien_color, gun_color, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => d <= alien_color;
      WHEN "01" => d <= gun_color;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_2 : c2_t7_basic_alien
      PORT MAP (
         clock          => clk,
         enable         => enable,
         hit            => btn(0),
         rst_n          => rst_n,
         alien_color    => alien_color,
         alien_defeated => OPEN,
         x_coord        => x_coord,
         y_coord        => y_coord
      );
   U_3 : c3_t1_gun_module
      PORT MAP (
         btn        => btn,
         clk        => clk,
         enable     => enable,
         gun_px_idx => gun_px_idx,
         rst_n      => rst_n,
         gun_color  => gun_color,
         x_coord    => x_coord1,
         y_coord    => y_coord1
      );
   U_0 : c3_t2_write_sequencer
      PORT MAP (
         clk           => clk,
         rst_n         => rst_n,
         write_ready   => w_rdy,
         enable        => enable,
         frame_done    => frame_done,
         gun_px_idx    => gun_px_idx,
         module_select => module_select,
         write         => write
      );
   U_1 : z_black_box_y
      PORT MAP (
         clk            => clk,
         color_BGR      => q2,
         frame_done     => frame_done,
         rst_n          => rst_n,
         write          => write,
         x_coord        => q,
         y_coord        => q1,
         if_you_name    => OPEN,
         iotre_will     => OPEN,
         like_this      => OPEN,
         of_this_course => of_this_course,
         throw_you_out  => OPEN,
         w_rdy          => w_rdy,
         your_signals   => OPEN
      );

END struct;
