-- VHDL Entity alien_game_lib.c3_t3_button_debounce.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-708-SPC)
--          at - 15:29:48 24.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t3_button_debounce IS
   PORT( 
      btn_in  : IN     std_logic;
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      btn_out : OUT    std_logic
   );

-- Declarations

END c3_t3_button_debounce ;

--
-- VHDL Architecture alien_game_lib.c3_t3_button_debounce.fsm
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-706-SPC)
--          at - 15:02:58 25.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c3_t3_button_debounce IS

   TYPE STATE_TYPE IS (
      start,
      s0,
      forced_to_1,
      forced_to_0
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(16 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s0 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= start;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      btn_in,
      csm_timeout,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s0 <= '0';
      CASE current_state IS
         WHEN start => 
            IF (btn_in = '1') THEN 
               next_state <= forced_to_1;
            ELSE
               next_state <= start;
            END IF;
         WHEN s0 => 
            IF (csm_timeout = '1' AND (btn_in = '1')) THEN 
               next_state <= forced_to_0;
            ELSIF (csm_timeout = '1' AND (btn_in = '0')) THEN 
               next_state <= start;
            ELSE
               next_state <= s0;
            END IF;
         WHEN forced_to_1 => 
            next_state <= s0;
            csm_to_s0 <= '1';
         WHEN forced_to_0 => 
            IF (btn_in = '0') THEN 
               next_state <= s0;
               csm_to_s0 <= '1';
            ELSE
               next_state <= forced_to_0;
            END IF;
         WHEN OTHERS =>
            next_state <= start;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      btn_out <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN start => 
            btn_out <= '0';
         WHEN s0 => 
            btn_out <= '0';
         WHEN forced_to_1 => 
            btn_out <= '1';
         WHEN forced_to_0 => 
            btn_out<='0';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s0
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s0 = '1') THEN
         csm_next_timer <= "11000011010011111"; -- no cycles(100000)-1=99999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
