-- VHDL Entity alien_game_lib.c3_t4_bullet_flight.symbol
--
-- Created:
--          by - Thinkpad X1.UNKNOWN (LENOVO-PC)
--          at - 19:00:25 10/24/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t4_bullet_flight IS
   PORT( 
      btn           : IN     std_logic_vector (3 DOWNTO 0);
      clk           : IN     std_logic;
      en            : IN     std_logic;
      gun_x         : IN     std_logic_vector (7 DOWNTO 0);
      rst_n         : IN     std_logic;
      bullet_colour : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x      : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t4_bullet_flight ;

--
-- VHDL Architecture alien_game_lib.c3_t4_bullet_flight.struct
--
-- Created:
--          by - Thinkpad X1.UNKNOWN (LENOVO-PC)
--          at - 19:00:25 10/24/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t4_bullet_flight IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d              : std_logic_vector(7 DOWNTO 0);
   SIGNAL d1             : std_logic_vector(23 DOWNTO 0);
   SIGNAL din1           : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2           : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout           : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1          : std_logic_vector(23 DOWNTO 0);
   SIGNAL out_left_shift : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL bullet_y_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic_vector(23 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t3_left_shifter
   PORT (
      in_left_shift  : IN     std_logic_vector (7 DOWNTO 0);
      out_left_shift : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t3_left_shifter USE ENTITY alien_game_lib.c2_t3_left_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   bullet_y_internal <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= d;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   bullet_x <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= gun_x;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'adff'
   bullet_colour <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_9reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_9reg_cval <= d1;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   din1 <= "00010000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout1 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din2 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(bullet_y_internal, din1, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => dout <= bullet_y_internal;
      WHEN '1' => dout <= din1;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(bullet_y_internal, out_left_shift, en)
   BEGIN
      CASE en IS
      WHEN '0' => d <= bullet_y_internal;
      WHEN '1' => d <= out_left_shift;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(dout1, din2, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => d1 <= dout1;
      WHEN '1' => d1 <= din2;
      WHEN OTHERS => d1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_0 : c2_t3_left_shifter
      PORT MAP (
         in_left_shift  => dout,
         out_left_shift => out_left_shift
      );

   -- Implicit buffered output assignments
   bullet_y <= bullet_y_internal;

END struct;
