-- VHDL Entity alien_game_lib.c3_t1_gun_module.symbol
--
-- Created:
--          by - Thinkpad X1.UNKNOWN (LENOVO-PC)
--          at - 10:14:21 10/16/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_gun_module IS
   PORT( 
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic;
      enable     : IN     std_logic;
      gun_px_idx : IN     std_logic_vector (2 DOWNTO 0);
      rst        : IN     std_logic;
      gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_gun_module ;

--
-- VHDL Architecture alien_game_lib.c3_t1_gun_module.struct
--
-- Created:
--          by - Thinkpad X1.UNKNOWN (LENOVO-PC)
--          at - 10:14:20 10/16/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t1_gun_module IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d     : std_logic_vector(7 DOWNTO 0);
   SIGNAL d1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL d2    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6 : std_logic_vector(7 DOWNTO 0);
   SIGNAL q     : std_logic_vector(7 DOWNTO 0);
   SIGNAL q1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL q2    : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_8' of 'adff'
   SIGNAL mw_U_8reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c3_t1_pixel_shifter
   PORT (
      end_sel   : IN     std_logic ;
      pixel_in  : IN     std_logic_vector (7 DOWNTO 0);
      selector  : IN     std_logic_vector (1 DOWNTO 0);
      pixel_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_pixel_shifter USE ENTITY alien_game_lib.c3_t1_pixel_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'adff'
   q <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_6reg_cval <= "00001010";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_6reg_cval <= d;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   q1 <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_7reg_cval <= "00001000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= d1;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'adff'
   q2 <= mw_U_8reg_cval;
   u_8seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_8reg_cval <= "00000100";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_8reg_cval <= d2;
      END IF;
   END PROCESS u_8seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout <= btn(1) AND enable;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout1 <= enable AND btn(3);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   gun_color <= "100000001000000010000000";

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout4 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout5 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout6 <= "00100000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'merge'
   dout2 <= dout1 & dout;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(q, q1, q2, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "000" => x_coord <= q;
      WHEN "001" => x_coord <= q1;
      WHEN "010" => x_coord <= q2;
      WHEN "011" => x_coord <= q;
      WHEN "100" => x_coord <= q1;
      WHEN "101" => x_coord <= q2;
      WHEN "110" => x_coord <= q1;
      WHEN "111" => x_coord <= q1;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'mux'
   u_11combo_proc: PROCESS(dout4, dout5, dout6, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "000" => y_coord <= dout4;
      WHEN "001" => y_coord <= dout4;
      WHEN "010" => y_coord <= dout4;
      WHEN "011" => y_coord <= dout5;
      WHEN "100" => y_coord <= dout5;
      WHEN "101" => y_coord <= dout5;
      WHEN "110" => y_coord <= dout6;
      WHEN "111" => y_coord <= dout6;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_11combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'or'
   dout3 <= q(7) OR q2(0);

   -- Instance port mappings.
   U_13 : c3_t1_pixel_shifter
      PORT MAP (
         end_sel   => dout3,
         pixel_in  => q,
         selector  => dout2,
         pixel_out => d
      );
   U_14 : c3_t1_pixel_shifter
      PORT MAP (
         end_sel   => dout3,
         pixel_in  => q1,
         selector  => dout2,
         pixel_out => d1
      );
   U_15 : c3_t1_pixel_shifter
      PORT MAP (
         end_sel   => dout3,
         pixel_in  => q2,
         selector  => dout2,
         pixel_out => d2
      );

END struct;
