-- VHDL Entity alien_game_lib.c3_t4_bullet_flight.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-711-SPC)
--          at - 17:24:10 24.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t4_bullet_flight IS
   PORT( 
      btn_bullet  : IN     std_logic;
      clk         : IN     std_logic;
      gun_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      rst_n       : IN     std_logic;
      x_coord_bul : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord_bul : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t4_bullet_flight ;

--
-- VHDL Architecture alien_game_lib.c3_t4_bullet_flight.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-711-SPC)
--          at - 17:24:04 24.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t4_bullet_flight IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1           : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout           : std_logic_vector(7 DOWNTO 0);
   SIGNAL out_left_shift : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL y_coord_bul_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t3_left_shifter
   PORT (
      in_left_shift  : IN     std_logic_vector (7 DOWNTO 0);
      out_left_shift : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t3_left_shifter USE ENTITY alien_game_lib.c2_t3_left_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   y_coord_bul_internal <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= out_left_shift;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   x_coord_bul <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= gun_x_coord;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   din1 <= "00010000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(y_coord_bul_internal, din1, btn_bullet)
   BEGIN
      CASE btn_bullet IS
      WHEN '0' => dout <= y_coord_bul_internal;
      WHEN '1' => dout <= din1;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_0 : c2_t3_left_shifter
      PORT MAP (
         in_left_shift  => dout,
         out_left_shift => out_left_shift
      );

   -- Implicit buffered output assignments
   y_coord_bul <= y_coord_bul_internal;

END struct;
