-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-716-SPC)
--          at - 16:36:32 29.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      hit      : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-716-SPC)
--          at - 16:36:27 29.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout11 : std_logic;
   SIGNAL dout12 : std_logic;
   SIGNAL dout13 : std_logic;
   SIGNAL dout14 : std_logic;
   SIGNAL dout15 : std_logic;
   SIGNAL dout16 : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_16' of 'adff'
   SIGNAL mw_U_16reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_16' of 'adff'
   hit <= mw_U_16reg_cval;
   u_16seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_16reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_16reg_cval <= dout16;
      END IF;
   END PROCESS u_16seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout <= alien_x(7) AND bullet_x(7);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout1 <= alien_x(6) AND bullet_x(6);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout2 <= alien_x(5) AND bullet_x(5);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout3 <= alien_x(4) AND bullet_x(4);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout4 <= alien_x(3) AND bullet_x(3);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout5 <= alien_x(2) AND bullet_x(2);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout6 <= alien_x(1) AND bullet_x(1);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout7 <= alien_x(0) AND bullet_x(0);

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout15 <= alien_y(0) AND bullet_y(0);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   dout16 <= dout14 AND dout15;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'or'
   dout8 <= dout OR dout1;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'or'
   dout9 <= dout2 OR dout3;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'or'
   dout10 <= dout4 OR dout5;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'or'
   dout11 <= dout6 OR dout7;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'or'
   dout12 <= dout8 OR dout9;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'or'
   dout13 <= dout10 OR dout11;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'or'
   dout14 <= dout12 OR dout13;

   -- Instance port mappings.

END struct;
