-- VHDL Entity alien_game_lib.c4_t4_shield_inital_reset.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-707-SPC)
--          at - 12:04:57 20.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t4_shield_inital_reset IS
   PORT( 
      clk   : IN     std_logic;
      rst_n : IN     std_logic;
      done  : OUT    std_logic;
      s_rst : OUT    std_logic
   );

-- Declarations

END c4_t4_shield_inital_reset ;

--
-- VHDL Architecture alien_game_lib.c4_t4_shield_inital_reset.fsm
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-707-SPC)
--          at - 12:24:39 20.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c4_t4_shield_inital_reset IS

   TYPE STATE_TYPE IS (
      start,
      s2,
      s0,
      s1
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(10 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(10 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s2 : std_logic;
   SIGNAL csm_to_s0 : std_logic;
   SIGNAL csm_to_s1 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= start;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s2 <= '0';
      csm_to_s0 <= '0';
      csm_to_s1 <= '0';
      CASE current_state IS
         WHEN start => 
            IF (rst_n = '1') THEN 
               next_state <= s2;
               csm_to_s2 <= '1';
            ELSE
               next_state <= start;
            END IF;
         WHEN s2 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s0;
               csm_to_s0 <= '1';
            ELSE
               next_state <= s2;
            END IF;
         WHEN s0 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s1;
               csm_to_s1 <= '1';
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= start;
            ELSE
               next_state <= s1;
            END IF;
         WHEN OTHERS =>
            next_state <= start;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      done <= '0';
      s_rst <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            s_rst <= '1';
         WHEN s1 => 
            done<= '1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s2,
      csm_to_s0,
      csm_to_s1
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s2 = '1') THEN
         csm_next_timer <= "00000001001"; -- no cycles(10)-1=9
      ELSIF (csm_to_s0 = '1') THEN
         csm_next_timer <= "00000000101"; -- no cycles(6)-1=5
      ELSIF (csm_to_s1 = '1') THEN
         csm_next_timer <= "10111011011"; -- no cycles(1500)-1=1499
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
