-- VHDL Entity alien_game_lib.c4_t3_pause_block.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-716-SPC)
--          at - 16:11:36 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t3_pause_block IS
   PORT( 
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      sw0     : IN     std_logic;
      btn_out : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END c4_t3_pause_block ;

--
-- VHDL Architecture alien_game_lib.c4_t3_pause_block.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-714-SPC)
--          at - 11:57:01 22.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t3_pause_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout1 <= btn(0) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout2 <= btn(1) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout3 <= btn(2) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout4 <= btn(3) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'inv'
   dout <= NOT(sw0);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'merge'
   btn_out <= dout4 & dout3 & dout2 & dout1;

   -- Instance port mappings.

END struct;
