-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-704-SPC)
--          at - 13:56:10  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      hit      : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-704-SPC)
--          at - 13:56:04  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1   : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout11 : std_logic;
   SIGNAL dout12 : std_logic;
   SIGNAL dout13 : std_logic;
   SIGNAL dout14 : std_logic;
   SIGNAL dout16 : std_logic;
   SIGNAL dout17 : std_logic;
   SIGNAL dout18 : std_logic;
   SIGNAL dout19 : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout20 : std_logic;
   SIGNAL dout21 : std_logic;
   SIGNAL dout22 : std_logic;
   SIGNAL dout23 : std_logic;
   SIGNAL dout24 : std_logic;
   SIGNAL dout25 : std_logic;
   SIGNAL dout26 : std_logic;
   SIGNAL dout27 : std_logic;
   SIGNAL dout28 : std_logic;
   SIGNAL dout29 : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;
   SIGNAL hit_in : std_logic;


   -- Component Declarations
   COMPONENT c4_t1_hit_debounce
   PORT (
      clk     : IN     std_logic ;
      hit_in  : IN     std_logic ;
      rst_n   : IN     std_logic ;
      hit_out : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_hit_debounce USE ENTITY alien_game_lib.c4_t1_hit_debounce;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout <= alien_x(7) AND bullet_x(7);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout1 <= alien_x(6) AND bullet_x(6);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout2 <= alien_x(5) AND bullet_x(5);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout3 <= alien_x(4) AND bullet_x(4);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout4 <= alien_x(3) AND bullet_x(3);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout5 <= alien_x(2) AND bullet_x(2);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout6 <= alien_x(1) AND bullet_x(1);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout7 <= alien_x(0) AND bullet_x(0);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   hit_in <= dout14 AND din1;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'and'
   dout23 <= alien_y(7) AND bullet_y(7);

   -- ModuleWare code(v1.12) for instance 'U_20' of 'and'
   dout21 <= alien_y(6) AND bullet_y(6);

   -- ModuleWare code(v1.12) for instance 'U_22' of 'and'
   dout29 <= alien_y(5) AND bullet_y(5);

   -- ModuleWare code(v1.12) for instance 'U_24' of 'and'
   dout17 <= alien_y(4) AND bullet_y(4);

   -- ModuleWare code(v1.12) for instance 'U_26' of 'and'
   dout18 <= alien_y(3) AND bullet_y(3);

   -- ModuleWare code(v1.12) for instance 'U_28' of 'and'
   dout24 <= alien_y(2) AND bullet_y(2);

   -- ModuleWare code(v1.12) for instance 'U_30' of 'and'
   dout25 <= alien_y(1) AND bullet_y(1);

   -- ModuleWare code(v1.12) for instance 'U_32' of 'and'
   dout19 <= alien_y(0) AND bullet_y(0);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'or'
   dout8 <= dout OR dout1;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'or'
   dout9 <= dout2 OR dout3;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'or'
   dout10 <= dout4 OR dout5;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'or'
   dout11 <= dout6 OR dout7;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'or'
   dout12 <= dout8 OR dout9;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'or'
   dout13 <= dout10 OR dout11;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'or'
   dout14 <= dout12 OR dout13;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'or'
   dout20 <= dout23 OR dout21;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'or'
   dout27 <= dout20 OR dout28;

   -- ModuleWare code(v1.12) for instance 'U_23' of 'or'
   dout28 <= dout29 OR dout17;

   -- ModuleWare code(v1.12) for instance 'U_25' of 'or'
   din1 <= dout27 OR dout16;

   -- ModuleWare code(v1.12) for instance 'U_27' of 'or'
   dout22 <= dout18 OR dout24;

   -- ModuleWare code(v1.12) for instance 'U_29' of 'or'
   dout16 <= dout22 OR dout26;

   -- ModuleWare code(v1.12) for instance 'U_31' of 'or'
   dout26 <= dout25 OR dout19;

   -- Instance port mappings.
   U_16 : c4_t1_hit_debounce
      PORT MAP (
         clk     => clk,
         hit_in  => hit_in,
         rst_n   => rst_n,
         hit_out => hit
      );

END struct;
