-- VHDL Entity alien_game_lib.c5_t2_register_row.symbol
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-709-SPC)
--          at - 15:50:51 27.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t2_register_row IS
   PORT( 
      clk      : IN     std_logic;
      nullify  : IN     std_logic;
      pixd_in  : IN     std_logic_vector (23 DOWNTO 0);
      read_en  : IN     std_logic;
      rst_n    : IN     std_logic;
      write    : IN     std_logic;
      xr       : IN     std_logic_vector (7 DOWNTO 0);
      xw       : IN     std_logic_vector (7 DOWNTO 0);
      pixd_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c5_t2_register_row ;

--
-- VHDL Architecture alien_game_lib.c5_t2_register_row.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-709-SPC)
--          at - 15:50:51 27.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t2_register_row IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout      : std_logic;
   SIGNAL dout1     : std_logic;
   SIGNAL dout2     : std_logic;
   SIGNAL dout3     : std_logic;
   SIGNAL dout4     : std_logic;
   SIGNAL dout5     : std_logic;
   SIGNAL dout6     : std_logic;
   SIGNAL dout7     : std_logic;
   SIGNAL nullify1  : std_logic;
   SIGNAL nullify2  : std_logic;
   SIGNAL nullify3  : std_logic;
   SIGNAL nullify4  : std_logic;
   SIGNAL nullify5  : std_logic;
   SIGNAL nullify6  : std_logic;
   SIGNAL nullify7  : std_logic;
   SIGNAL nullify8  : std_logic;
   SIGNAL pixd_out1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out3 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out4 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out5 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out6 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out7 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixd_out8 : std_logic_vector(23 DOWNTO 0);
   SIGNAL read_en1  : std_logic;


   -- Component Declarations
   COMPONENT c5_t2_register_single
   PORT (
      clk      : IN     std_logic ;
      nullify  : IN     std_logic ;
      pixd_in  : IN     std_logic_vector (23 DOWNTO 0);
      read_en  : IN     std_logic ;
      rst_n    : IN     std_logic ;
      write    : IN     std_logic ;
      pixd_out : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c5_t2_register_single USE ENTITY alien_game_lib.c5_t2_register_single;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout7 <= write AND xw(0);

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   dout6 <= write AND xw(1);

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   dout5 <= write AND xw(2);

   -- ModuleWare code(v1.12) for instance 'U_11' of 'and'
   dout4 <= write AND xw(3);

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   dout3 <= write AND xw(4);

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout2 <= write AND xw(5);

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout1 <= write AND xw(6);

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout <= write AND xw(7);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   nullify8 <= xr(0) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'and'
   nullify1 <= xr(1) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'and'
   nullify2 <= xr(2) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_20' of 'and'
   nullify3 <= xr(3) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'and'
   nullify4 <= xr(4) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_22' of 'and'
   nullify5 <= xr(5) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_23' of 'and'
   nullify6 <= xr(6) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_24' of 'and'
   nullify7 <= xr(7) AND nullify;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'omux'
   u_16combo_proc: PROCESS(pixd_out8, pixd_out7, pixd_out6, pixd_out5, 
                           pixd_out4, pixd_out3, pixd_out2, pixd_out1, 
                           xr)
   BEGIN
      pixd_out <= (OTHERS => '0');
      CASE xr IS
      WHEN "00000001" => pixd_out <= pixd_out8;
      WHEN "00000010" => pixd_out <= pixd_out7;
      WHEN "00000100" => pixd_out <= pixd_out6;
      WHEN "00001000" => pixd_out <= pixd_out5;
      WHEN "00010000" => pixd_out <= pixd_out4;
      WHEN "00100000" => pixd_out <= pixd_out3;
      WHEN "01000000" => pixd_out <= pixd_out2;
      WHEN "10000000" => pixd_out <= pixd_out1;
      WHEN OTHERS => pixd_out <= (OTHERS => '0');
      END CASE;
   END PROCESS u_16combo_proc;

   -- Instance port mappings.
   U_0 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify8,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout7,
         pixd_out => pixd_out8
      );
   U_1 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify1,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout6,
         pixd_out => pixd_out7
      );
   U_2 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify2,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout5,
         pixd_out => pixd_out6
      );
   U_3 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify3,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout4,
         pixd_out => pixd_out5
      );
   U_4 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify4,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout3,
         pixd_out => pixd_out4
      );
   U_5 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify5,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout2,
         pixd_out => pixd_out3
      );
   U_6 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify6,
         pixd_in  => pixd_in,
         read_en  => read_en,
         rst_n    => rst_n,
         write    => dout1,
         pixd_out => pixd_out2
      );
   U_7 : c5_t2_register_single
      PORT MAP (
         clk      => clk,
         nullify  => nullify7,
         pixd_in  => pixd_in,
         read_en  => read_en1,
         rst_n    => rst_n,
         write    => dout,
         pixd_out => pixd_out1
      );

END struct;
