-- VHDL Entity tb_lib.tb_bin2onehot_tt.symbol
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 15:32:10 06/12/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_bin2onehot_tt IS
-- Declarations

END tb_bin2onehot_tt ;

--
-- VHDL Architecture tb_lib.tb_bin2onehot_tt.struct
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 13:20:29 08/21/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_bin2onehot_tt IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL correct : std_logic;
   SIGNAL res     : std_logic_vector(7 DOWNTO 0);
   SIGNAL to_duv  : std_logic_vector(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT tt_tester
   PORT (
      res     : IN     std_logic_vector (7 DOWNTO 0);
      correct : OUT    std_logic ;
      to_duv  : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tt_tester USE ENTITY tb_lib.tt_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : tt_tester
      PORT MAP (
         res     => res,
         correct => correct,
         to_duv  => to_duv
      );

END struct;
