-- VHDL Entity tb_lib.tb_decrementer.symbol
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 13:34:35 06/11/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_decrementer IS
-- Declarations

END tb_decrementer ;

--
-- VHDL Architecture tb_lib.tb_decrementer.struct
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 12:54:48 08/21/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL correct : std_logic;
   SIGNAL res     : std_logic_vector(2 DOWNTO 0);
   SIGNAL to_duv  : std_logic_vector(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT decrementer_tester_block
   PORT (
      res     : IN     std_logic_vector (2 DOWNTO 0);
      correct : OUT    std_logic ;
      to_duv  : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : decrementer_tester_block USE ENTITY tb_lib.decrementer_tester_block;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : decrementer_tester_block
      PORT MAP (
         res     => res,
         correct => correct,
         to_duv  => to_duv
      );

END struct;
