-- VHDL Entity tb_lib.tb_pixel_conf.symbol
--
-- Created:
--          by - kayra
--          at - 09:38:55 07/03/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_pixel_conf IS
-- Declarations

END tb_pixel_conf ;

--
-- VHDL Architecture tb_lib.tb_pixel_conf.struct
--
-- Created:
--          by - kayra
--          at - 16:16:05 09/09/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_pixel_conf IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color : std_logic_vector(23 DOWNTO 0);
   SIGNAL x     : std_logic_vector(7 DOWNTO 0);
   SIGNAL y     : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT pixel_conf_tester
   PORT (
      color : IN     std_logic_vector (23 DOWNTO 0);
      x     : IN     std_logic_vector (7 DOWNTO 0);
      y     : IN     std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : pixel_conf_tester USE ENTITY tb_lib.pixel_conf_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : pixel_conf_tester
      PORT MAP (
         color => color,
         x     => x,
         y     => y
      );

END struct;
