-- VHDL Entity tb_lib.tb_pixel_conf.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-712-SPC)
--          at - 09:38:55 07/03/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_pixel_conf IS
-- Declarations

END tb_pixel_conf ;

--
-- VHDL Architecture tb_lib.tb_pixel_conf.struct
--
-- Created:
--          by - wirdatma.UNKNOWN (HTC219-712-SPC)
--          at - 10:46:06 27.09.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_pixel_conf IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color : std_logic_vector(23 DOWNTO 0);
   SIGNAL x     : std_logic_vector(7 DOWNTO 0);
   SIGNAL y     : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c1_t3_hello_led
   PORT (
      color : OUT    std_logic ;
      x     : OUT    std_logic ;
      y     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT pixel_conf_tester
   PORT (
      color : IN     std_logic_vector (23 DOWNTO 0);
      x     : IN     std_logic_vector (7 DOWNTO 0);
      y     : IN     std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t3_hello_led USE ENTITY alien_game_lib.c1_t3_hello_led;
   FOR ALL : pixel_conf_tester USE ENTITY tb_lib.pixel_conf_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : c1_t3_hello_led
      PORT MAP (
         color => color,
         x     => x,
         y     => y
      );
   U_1 : pixel_conf_tester
      PORT MAP (
         color => color,
         x     => x,
         y     => y
      );

END struct;
