-- VHDL Entity tb_lib.tb_shift_up.symbol
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 13:29:49 07/30/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_shift_up IS
-- Declarations

END tb_shift_up ;

--
-- VHDL Architecture tb_lib.tb_shift_up.struct
--
-- Created:
--          by - kayra.UNKNOWN (WS-11696-PC)
--          at - 13:24:09 08/21/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_shift_up IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL correct         : std_logic;
   SIGNAL from_up_shifter : std_logic_vector(7 DOWNTO 0);
   SIGNAL to_up_shifter   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT shift_up_tester
   PORT (
      from_up_shifter : IN     std_logic_vector (7 DOWNTO 0);
      correct         : OUT    std_logic;
      to_up_shifter   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : shift_up_tester USE ENTITY tb_lib.shift_up_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : shift_up_tester
      PORT MAP (
         from_up_shifter => from_up_shifter,
         correct         => correct,
         to_up_shifter   => to_up_shifter
      );

END struct;
