-- VHDL Entity tb_lib.tb_serial_tx.symbol
--
-- Created:
--          by - kayra
--          at - 15:06:14 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_serial_tx IS
-- Declarations

END tb_serial_tx ;

--
-- VHDL Architecture tb_lib.tb_serial_tx.struct
--
-- Created:
--          by - kayra
--          at - 16:00:09 09/20/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY tb_lib;

ARCHITECTURE struct OF tb_serial_tx IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit_in   : std_logic;
   SIGNAL clk      : std_logic;
   SIGNAL ready    : std_logic;
   SIGNAL rst_n    : std_logic;
   SIGNAL sck      : std_logic;
   SIGNAL sda      : std_logic;
   SIGNAL transmit : std_logic;


   -- Component Declarations
   COMPONENT tx_tester_struct
   PORT (
      rdy      : IN     std_logic ;
      sck      : IN     std_logic ;
      sda      : IN     std_logic ;
      bit_in   : OUT    std_logic ;
      clk      : OUT    std_logic ;
      rst_n    : OUT    std_logic ;
      transmit : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tx_tester_struct USE ENTITY tb_lib.tx_tester_struct;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : tx_tester_struct
      PORT MAP (
         rdy      => ready,
         sck      => sck,
         sda      => sda,
         bit_in   => bit_in,
         clk      => clk,
         rst_n    => rst_n,
         transmit => transmit
      );

END struct;
